name    'openstackci-apparmor'
version '0.0.1'
source 'git://git.openstack.org/openstack-infra/puppet-apparmor.git'
author 'OpenStack Continuous Integration'
license 'Apache License, Version 2.0'
summary 'apparmor module'
description 'apparmor module'
project_page 'https://git.openstack.org/cgit/openstack-infra/puppet-apparmor'
