name    'openstackci-apparmor'
version '0.0.1'
source 'https://github.com/openstack-ci/puppet-apparmor.git'
author 'OpenStack Continuous Integration'
license 'Apache License, Version 2.0'
summary 'apparmor module'
description 'apparmor module'
project_page 'https://github.com/openstack-ci/puppet-apparmor'
